"""Paper-agnostic TeX value store.

Collects scalar paper values (from polars queries or plain Python values) and
writes them to a ``values.tex`` file backed by a ``\\setval``/``\\getval``
csname key-value store, or to a Markdown table for contexts without
``\\getval`` (presentations, notes) where values are copied by hand. Metric
definitions stay in the paper repository; this module only owns registration,
collection, and emission.
"""

import re
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Callable, Optional, Union

import polars as pl
from loguru import logger
from matplotlib.ticker import EngFormatter

Formatter = Union[str, Callable[[Any], str]]

_NAME_FORBIDDEN = re.compile(r"[\\{}%#\s]")

# Escaped in a single pass so replacement text (e.g. the braces in
# \textbackslash{}) is never re-escaped.
_TEX_ESCAPES = {
    "\\": r"\textbackslash{}",
    "{": r"\{",
    "}": r"\}",
    "%": r"\%",
    "&": r"\&",
    "#": r"\#",
    "_": r"\_",
    "$": r"\$",
}
_TEX_ESCAPE_RE = re.compile(r"[\\{}%&#_$]")

_PREAMBLE = (
    "% auto-generated by ndpi.tex.TexValues -- do not edit\n"
    "% requires \\usepackage{xspace} when xspace is enabled\n"
    "\\providecommand{\\setval}[2]{\\expandafter\\gdef\\csname texval@#1\\endcsname{#2}}\n"
    "\\providecommand{\\getval}[1]{%\n"
    "  \\ifcsname texval@#1\\endcsname\\csname texval@#1\\endcsname\n"
    "  \\else\\errmessage{Unknown tex value: #1}\\fi}"
)


def _escape_tex(text: str) -> str:
    return _TEX_ESCAPE_RE.sub(lambda m: _TEX_ESCAPES[m.group()], text)


def _escape_markdown(text: str) -> str:
    # only the cell separator breaks table structure; everything else is
    # kept verbatim so values stay copy-pasteable
    return text.replace("|", "\\|")


@dataclass
class _Entry:
    value: Any
    fmt: Optional[Formatter]
    note: Optional[str]
    emit: bool
    error: Optional[str] = None

    @property
    def errored(self) -> bool:
        return self.error is not None

    @property
    def unresolved(self) -> bool:
        return self.error is None and isinstance(
            self.value, (pl.LazyFrame, pl.DataFrame)
        )


class TexValues:
    """Insertion-ordered registry of named scalar values for a paper.

    Workflow: ``register()`` LazyFrame queries, eager DataFrames, or plain
    values; ``collect()`` to resolve them to scalars; optionally register
    derived plain values computed from ``store[name]``; ``write()`` the
    ``values.tex`` file.
    """

    def __init__(self) -> None:
        self._entries: dict[str, _Entry] = {}

    def register(
        self,
        name: str,
        value: Any,
        fmt: Optional[Formatter] = None,
        note: Optional[str] = None,
        emit: bool = True,
    ) -> "TexValues":
        """Register a value under ``name``.

        Args:
            name: Key used in ``\\getval{name}``. Must not contain
                ``\\ { } % #`` or whitespace.
            value: A 1x1 ``pl.LazyFrame`` query (collected and extracted in
                ``collect()``), a 1x1 ``pl.DataFrame`` (extracted in
                ``collect()`` without collection), or any other value (stored
                verbatim, resolved immediately, no postprocessing).
            fmt: Python format spec string (e.g. ``",.1f"``) or callable
                ``value -> str``. Applied only in ``write()``.
            note: Comment written next to the entry in the output file, e.g.
                ``"FIXME hardcoded, see ..."``. Must not contain newlines.
            emit: When False the entry is resolved and readable via
                ``store[name]`` but never written to the output file.

        Returns:
            self, for chaining.
        """
        if not name or _NAME_FORBIDDEN.search(name):
            raise ValueError(
                f"invalid tex value name {name!r}: must be non-empty and must not "
                "contain '\\', '{', '}', '%', '#', or whitespace"
            )
        if name in self._entries:
            raise ValueError(f"duplicate tex value name {name!r}")
        if note is not None and ("\n" in note or "\r" in note):
            raise ValueError(
                f"note for tex value {name!r} contains a newline, which would "
                "terminate the TeX comment and leak the remainder as live code"
            )
        self._entries[name] = _Entry(value=value, fmt=fmt, note=note, emit=emit)
        return self

    def collect(
        self, individual: bool = False, strict: bool = False, **collect_kwargs: Any
    ) -> "TexValues":
        """Resolve all pending LazyFrame/DataFrame entries to scalars.

        LazyFrame entries are collected — batched via ``pl.collect_all``
        (parallelism + common-subplan elimination) by default, or one at a
        time with ``individual=True`` (bounded memory). If the batched
        ``collect_all`` raises, all pending entries fall back to individual
        collection so one bad query doesn't take down the batch.

        Every resulting/registered DataFrame is then validated to be exactly
        1 row x 1 column and non-null, and replaced by ``df.item()``.

        Args:
            individual: Collect LazyFrames one at a time instead of batched.
            strict: Raise on the first failure instead of isolating it. With
                the default ``False``, a failing entry logs a warning and is
                stored as errored; ``write()`` renders it as an ``ERR``
                placeholder (if ``emit=True``).
            **collect_kwargs: Passed through to ``pl.collect_all`` /
                ``LazyFrame.collect``.

        Returns:
            self, for chaining. Idempotent: already resolved or errored
            entries are skipped (errored entries are not retried).
        """
        lazy = {
            name: entry
            for name, entry in self._entries.items()
            if entry.unresolved and isinstance(entry.value, pl.LazyFrame)
        }
        if lazy:
            if individual:
                self._collect_individual(lazy, strict, collect_kwargs)
            else:
                try:
                    frames = pl.collect_all(
                        [entry.value for entry in lazy.values()], **collect_kwargs
                    )
                    for entry, df in zip(lazy.values(), frames):
                        entry.value = df
                except Exception as exc:
                    logger.warning(
                        f"batched collect_all failed ({exc}); "
                        "falling back to individual collection"
                    )
                    self._collect_individual(lazy, strict, collect_kwargs)

        for name, entry in self._entries.items():
            if not (entry.unresolved and isinstance(entry.value, pl.DataFrame)):
                continue
            df = entry.value
            if df.height != 1 or df.width != 1:
                self._fail(
                    name,
                    entry,
                    f"tex value {name!r}: expected exactly 1 row x 1 column, "
                    f"got {df.height} rows x {df.width} columns",
                    strict,
                )
                continue
            item = df.item()
            if item is None:
                self._fail(name, entry, f"tex value {name!r} is null", strict)
                continue
            entry.value = item
        return self

    def _collect_individual(
        self, lazy: dict[str, _Entry], strict: bool, collect_kwargs: dict[str, Any]
    ) -> None:
        for name, entry in lazy.items():
            try:
                entry.value = entry.value.collect(**collect_kwargs)
            except Exception as exc:
                if strict:
                    raise
                self._fail(
                    name, entry, f"collecting tex value {name!r} failed: {exc}", False
                )

    @staticmethod
    def _fail(name: str, entry: _Entry, message: str, strict: bool) -> None:
        if strict:
            raise ValueError(message)
        entry.error = message
        logger.warning(message)

    def __getitem__(self, name: str) -> Any:
        """Raw resolved value, for post-collect derived computations."""
        if name not in self._entries:
            raise KeyError(f"unknown tex value {name!r}")
        entry = self._entries[name]
        if entry.errored:
            raise RuntimeError(
                f"tex value {name!r} errored during collect(): {entry.error}"
            )
        if entry.unresolved:
            raise RuntimeError(
                f"tex value {name!r} is not resolved yet; call collect() first"
            )
        return entry.value

    def __contains__(self, name: str) -> bool:
        return name in self._entries

    def write(self, path: Union[str, Path], xspace: bool = True) -> None:
        """Write all ``emit=True`` entries to ``path`` as ``\\setval`` lines.

        Args:
            path: Output file, typically ``values.tex``.
            xspace: Append ``\\xspace`` to every value (requires
                ``\\usepackage{xspace}`` in the paper).
        """
        self._require_resolved()
        lines = [_PREAMBLE]
        for name, entry in self._entries.items():
            if not entry.emit:
                continue
            if entry.errored:
                assert entry.error is not None
                comment = " ".join(entry.error.split())
                lines.append(f"\\setval{{{name}}}{{ERR}} % ERROR: {comment}")
                continue
            text = self._format(name, entry)
            value = _escape_tex(text)
            if xspace:
                value += "\\xspace"
            line = f"\\setval{{{name}}}{{{value}}}"
            if entry.note is not None:
                line += f" % {entry.note}"
            lines.append(line)
        Path(path).write_text("\n".join(lines) + "\n")

    def to_markdown(self) -> str:
        """Render all ``emit=True`` entries as a Markdown table.

        Values are formatted with the same ``fmt`` as in ``write()`` but
        without TeX escaping or ``\\xspace``, so they can be copied verbatim
        into presentations or notes. Errored entries render as ``ERR`` with
        the error message in the note column.

        Returns:
            The table as a string, ending in a newline.
        """
        self._require_resolved()
        rows = []
        for name, entry in self._entries.items():
            if not entry.emit:
                continue
            if entry.errored:
                assert entry.error is not None
                value = "ERR"
                note = f"ERROR: {' '.join(entry.error.split())}"
            else:
                value = self._format(name, entry)
                note = entry.note or ""
            rows.append((name, value, note))

        header = ("Name", "Value", "Note")
        if not any(note for _, _, note in rows):
            header = header[:2]
            rows = [row[:2] for row in rows]
        cells = [header, *(
            tuple(_escape_markdown(cell) for cell in row) for row in rows
        )]
        widths = [max(len(row[i]) for row in cells) for i in range(len(header))]
        lines = [
            "| " + " | ".join(cell.ljust(w) for cell, w in zip(row, widths)) + " |"
            for row in cells
        ]
        lines.insert(1, "|" + "|".join("-" * (w + 2) for w in widths) + "|")
        return "\n".join(lines) + "\n"

    def write_markdown(self, path: Union[str, Path]) -> None:
        """Write the ``to_markdown()`` table to ``path``, e.g. ``values.md``."""
        Path(path).write_text(self.to_markdown())

    def _require_resolved(self) -> None:
        unresolved = [
            name for name, entry in self._entries.items() if entry.unresolved
        ]
        if unresolved:
            raise RuntimeError(
                f"cannot write: unresolved entries {unresolved}; "
                "call collect() first"
            )

    @staticmethod
    def _format(name: str, entry: _Entry) -> str:
        if entry.fmt is None:
            text = str(entry.value)
        elif isinstance(entry.fmt, str):
            text = format(entry.value, entry.fmt)
        else:
            text = str(entry.fmt(entry.value))
        if "\n" in text or "\r" in text:
            raise ValueError(
                f"formatted value for tex value {name!r} contains a newline"
            )
        return text


def fmt_eng(places: int = 1) -> Callable[[Any], str]:
    """Engineering notation without a separator space, e.g. ``2.1M``, ``116.0k``.

    Args:
        places: Number of decimal places.
    """
    formatter = EngFormatter(places=places, sep="")

    def fmt(value: Any) -> str:
        return formatter(value)

    return fmt


def fmt_percent(digits: int = 0, factor: float = 1) -> Callable[[Any], str]:
    """Percentage, e.g. ``13.0`` -> ``13%`` (escaped to ``13\\%`` by the writer).

    Args:
        digits: Number of decimal places.
        factor: Multiplier applied before formatting; use 100 if the value is
            a fraction (e.g. ``0.13``) rather than already in percent.
    """

    def fmt(value: Any) -> str:
        return f"{value * factor:.{digits}f}%"

    return fmt


def fmt_date(spec: str = "%Y-%m-%d") -> Callable[[Any], str]:
    """Date/datetime via ``strftime``.

    Args:
        spec: ``strftime`` format specification.
    """

    def fmt(value: Any) -> str:
        return value.strftime(spec)

    return fmt
